import { z } from "zod";
import { createSimulatedTrip, resolveStreak } from "@/lib/mvp/scoring";
import { requireUser } from "@/lib/server/auth";
import { apiError, apiSuccess } from "@/lib/server/http";

const bodySchema = z.object({
  vehicleId: z.string().uuid().nullable().optional(),
  preset: z.enum(["safe_city", "mixed_city"]).default("safe_city"),
});

export async function POST(request: Request) {
  const auth = await requireUser();
  if (auth.error || !auth.supabase || !auth.user) return apiError(auth.error ?? "Unauthorized", auth.status);

  const parsed = bodySchema.safeParse(await request.json().catch(() => ({})));
  if (!parsed.success) return apiError("Invalid simulation request", 422, parsed.error.flatten());

  const { data: profile, error: profileError } = await auth.supabase
    .from("profiles")
    .select("current_streak,last_trip_date")
    .eq("id", auth.user.id)
    .single();
  if (profileError) return apiError("Could not load XP streak state", 500, profileError.message);

  const endedAt = new Date().toISOString();
  const streak = resolveStreak(profile.last_trip_date, Number(profile.current_streak ?? 0), endedAt);
  const result = createSimulatedTrip(parsed.data.vehicleId, parsed.data.preset, streak.streakDays, streak.firstTripOfDay);
  const { data, error } = await auth.supabase.rpc("record_trip_result", {
    p_vehicle_id: result.vehicleId,
    p_mode: result.mode,
    p_started_at: result.startedAt,
    p_ended_at: result.endedAt,
    p_distance_km: result.distanceKm,
    p_duration_seconds: result.durationSeconds,
    p_average_speed_kmh: result.averageSpeedKmh,
    p_maximum_speed_kmh: result.maximumSpeedKmh,
    p_overspeed_events: result.overspeedEvents,
    p_major_overspeed_events: result.majorOverspeedEvents,
    p_gps_quality: result.gpsQuality,
    p_safety_score: result.safetyScore,
    p_xp_earned: result.xpEarned,
    p_events: result.events,
    p_metadata: {
      preset: parsed.data.preset,
      disclosure: "Simulated trip generated by CrediSafe",
      xpVersion: result.xpBreakdown.version,
      xpBreakdown: result.xpBreakdown,
      rewardPointsEarned: result.rewardPointsEarned,
    },
  });

  if (error) return apiError("Could not save simulated trip", 500, error.message);
  return apiSuccess({ tripId: data, result }, 201);
}
